CREATE TABLE stores(id bigserial PRIMARY KEY, name text NOT NULL);
CREATE TABLE users(id bigserial PRIMARY KEY, store_id bigint NOT NULL REFERENCES stores, email text UNIQUE NOT NULL, password_hash text NOT NULL);
CREATE TABLE sessions(token_hash text PRIMARY KEY, user_id bigint NOT NULL REFERENCES users, expires_at timestamptz NOT NULL);
CREATE TABLE products(id bigserial PRIMARY KEY, store_id bigint NOT NULL REFERENCES stores, name text NOT NULL, price_cents bigint NOT NULL CHECK(price_cents BETWEEN 0 AND 100000000), stock bigint NOT NULL CHECK(stock>=0), UNIQUE(store_id,id));
CREATE TABLE orders(id bigserial PRIMARY KEY, store_id bigint NOT NULL REFERENCES stores, idempotency_key text NOT NULL, request_hash text NOT NULL, total_cents bigint NOT NULL CHECK(total_cents>=0), state text NOT NULL CHECK(state IN ('confirmed','preparing','ready','completed','cancelled')), financial_state text NOT NULL DEFAULT 'manual_pending' CHECK(financial_state IN ('manual_pending','manual_confirmed')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(store_id,idempotency_key), UNIQUE(store_id,id));
CREATE TABLE order_items(order_id bigint NOT NULL, store_id bigint NOT NULL, product_id bigint NOT NULL, name text NOT NULL, price_cents bigint NOT NULL, quantity bigint NOT NULL CHECK(quantity>0), FOREIGN KEY(store_id,order_id) REFERENCES orders(store_id,id), FOREIGN KEY(store_id,product_id) REFERENCES products(store_id,id));
CREATE TABLE audit(id bigserial PRIMARY KEY, store_id bigint NOT NULL REFERENCES stores, user_id bigint REFERENCES users, action text NOT NULL, entity_id bigint, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE jobs(id bigserial PRIMARY KEY, store_id bigint NOT NULL REFERENCES stores, kind text NOT NULL, payload jsonb NOT NULL, dedup_key text NOT NULL UNIQUE, attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), lease_until timestamptz, state text NOT NULL DEFAULT 'pending' CHECK(state IN ('pending','running','done','failed')), last_error_code text);
CREATE INDEX jobs_available ON jobs(available_at) WHERE state IN ('pending','running');
