const { chromium } = require('../tools/qa/node_modules/playwright');
const fs = require('fs'); const path = require('path');
const assert = require('assert');
const root = path.resolve(__dirname,'..');
const data = process.env.OPENFOOD_UI_TEST_DATA || path.join(root,'runtime','QA com espaços e ação');
const evidence = path.join(root,'docs','evidence');
const wait = ms => new Promise(r=>setTimeout(r,ms));
(async()=>{
 for(let i=0;i<90&&!fs.existsSync(path.join(data,'runtime.json'));i++)await wait(1000);
 const {URL:url}=JSON.parse(fs.readFileSync(path.join(data,'runtime.json'),'utf8'));
 const config=JSON.parse(fs.readFileSync(path.join(data,'config.json'),'utf8'));
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 fs.mkdirSync(evidence,{recursive:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url+'/#setup='+config.setup_token);
 await page.locator('#setup:not(.hidden)').waitFor();
 await page.screenshot({path:path.join(evidence,'setup-desktop.png'),fullPage:true});
 await page.locator('#setupForm [name=store]').fill('Loja de teste QA');
 await page.locator('#setupForm [name=email]').fill('qa@example.org');
 await page.locator('#setupForm [name=password]').fill('QA-test-only-password');
 await page.locator('#setupForm button').click();
 await page.locator('#login:not(.hidden)').waitFor();
 await page.locator('#loginForm [name=email]').fill('qa@example.org');
 await page.locator('#loginForm [name=password]').fill('QA-test-only-password');
 await page.locator('#loginForm button').click();
 await page.locator('#workspace:not(.hidden)').waitFor();
 await page.locator('#productForm [name=name]').fill('Produto de teste');
 await page.locator('#productForm [name=price]').fill('19,99');
 await page.locator('#productForm [name=stock]').fill('5');
 await page.locator('#productForm button').click();
 await page.locator('#products').getByText('Produto de teste').waitFor();
 await page.locator('#orderForm [name=quantity]').fill('2');
 await page.locator('#orderForm input[type=checkbox]').check();
 await page.locator('#orderForm button').click();
 await page.locator('#orders').getByText('R$ 39,98').waitFor();
 await page.locator('#orders').getByRole('button',{name:'Em preparo'}).click();
 await page.locator('#orders').getByRole('button',{name:'Pronto',exact:true}).click();
 await page.locator('#orders').getByRole('button',{name:'Concluído',exact:true}).click();
 await page.locator('#orders').getByText('Concluído',{exact:true}).waitFor();
 for(const [name,width,height] of [['desktop',1440,1000],['tablet',768,1024],['mobile',390,844]]){await page.setViewportSize({width,height});await page.screenshot({path:path.join(evidence,'operation-'+name+'.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'horizontal overflow '+name)}
 await page.setViewportSize({width:1440,height:1000});
 const diagnostics=await page.evaluate(async()=>{const r=await fetch('/api/diagnostics');return r.json()});
 assert(!JSON.stringify(diagnostics).includes(config.password),'password in diagnostics');assert(!JSON.stringify(diagnostics).includes(config.setup_token),'setup token in diagnostics');
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#backup').click()]);
 const dump=path.join(root,'runtime','qa-backup.dump');await download.saveAs(dump);assert(fs.readFileSync(dump).subarray(0,5).toString()==='PGDMP');
 await page.locator('#restoreFile').setInputFiles(dump);await page.locator('#restoreConfirm').fill('RESTAURAR');await page.locator('#restore').click();await page.locator('#login:not(.hidden)').waitFor({timeout:30000});
 await page.locator('#loginForm [name=email]').fill('qa@example.org');await page.locator('#loginForm [name=password]').fill('QA-test-only-password');await page.locator('#loginForm button').click();await page.locator('#workspace:not(.hidden)').waitFor();await page.locator('#orders').getByText('Concluído',{exact:true}).waitFor();
 assert(errors.length===0,errors.join('\n'));
 const result={date:'2026-10-02',environment:'Windows com ferramentas de desenvolvimento; Chrome headless; não ambiente limpo',passed:['setup','login','catalog','manual order','backend amount 3998 cents','order transitions','responsive widths','diagnostics without credentials','backup download','UI restore','session revocation','preserved completed order'],javascript_errors:errors,status:'PASS'};
 fs.writeFileSync(path.join(evidence,'test-results.json'),JSON.stringify(result,null,2));
 console.log(JSON.stringify(result));
 await page.evaluate(()=>fetch('/api/shutdown',{method:'POST',headers:{'X-OpenFood':'1'}}));await browser.close();
})().catch(e=>{console.error(e.message);process.exit(1)});
